var nameList = [
  "Ashwin",
  "Rashmi",
  "Ramya",
  "Ridhi",
  "Mathi",
  "Aditi",
  "Dhanya",
  "Manav",
  "Jitti",
  "Raju",
  "Ram",
  "Tanu",
  "Manu",
  "Tej",
  "Sham sharma",
  "Tejindar Bhalla",
  "Sharada",
  "Devi",
  "Aish",
  "Sachin",
  "Shashi",
  "Sasha",
  "Lily",
  "Pooja karkar",
  "Aalia",
  "Raj Bhat",
  "Mrunal Toplar",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Manya TJ",
  "Megha Bhalla",
];

export function generateRandomNames() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

const randomMessages = [
  "Hello, how are you?",
  "What are you up to?",
  "Hope you have a great day!❤️",
  "Just checking in!",
  "Any exciting plans for the weekend?",
  "Random message for you!💫",
  "Did you know that elephants are the only animals that cant jump?",
  "Hope you enjoy this random text!🚀",
  "Whats up Buddy",
  "Lets plan a get-together",
  "❤️❤️❤️❤️❤️",
  "🚀🚀🚀🚀🚀",
  "😂😂😂😂"

];

export function getRandomMessage() {
  const randomIndex = Math.floor(Math.random() * randomMessages.length);
  return randomMessages[randomIndex];
}
